package com.affinity.sk_facilities;

public class Constants {
    public static final String MY_PREFS_NAME = "MyPrefsFile";
    public static final String KEY_OTP_LOGGED_IN = "key_logged_in";
    public static final String KEY_SIGN_UPS = "Key_sign_ups";
    public static final String KEY_ONPAYMENT = "key_onpayment";
    public static final String KEY_ONTRIP = "key_ontrip";
    public static final String ARRIVED = "ARRIVED";
    public static final String KEY_ONTRIP2 = "key_ontrip2";
    public static final String REGISTER = "https://tranznexs.com/riderapi/registration";
    public static final String EDIT_PROFILE = "https://tranznexs.com/riderapi/edit-profile";
    public static final String user_id = "user_id";
    public static final String firstname = "firstname";
    public static final String lastname = "lastname";
    public static final String email_id = "email_id";
    public static final String password = "password";
    public static final String address = "address";
    public static final String state = "state";
    public static final String city = "city";
    public static final String image = "image";
    public static final String mobileno = "mobileno";
    public static final String country = "country";
    public static final String amount = "amount";
    public static final String pickupupLocation = "pickupupLocation";
    public static final String pickup_location = "pickup_location";
    public static final String pickup_locationlayout = "pickup_locationlayout";
    public static final String drop_locationlayout = "drop_locationlayout";
    public static final String current_loc_lat = "current_loc_lat";
    public static final String current_loc_lng = "current_loc_lng";
    public static final String drop_location = "drop_location";
    public static final String drop_latitude = "drop_latitude";
    public static final String pickup_longitude = "pickup_longitude";
    public static final String drop_longitude = "drop_longitude";
    public static final String pickup_latitude = "pickup_latitude";
    public static final String payment_type = "payment_type";
    public static final String Payment_method = "Payment_method";
    public static final String rateperkm = "rateperkm";
    public static final String bikeName = "bikeName";
    public static final String duration = "duration";
    public static final String destination = "destination";
    public static final String origin = "origin";
    public static final String distance = "distance";
    public static final String FAV_HOME = "fav_home";
    public static final String FAV_WORK = "fav_work";
    public static final String FAV_OTHER = "fav_other";
    public static final String Hourlyamount = "Hourlyamount";
}
